"""
Monitoring framework util class
"""

TYPE = "type"
NAME = "name"
QUERY = "sql"
BQ_DATA_FETCHER = "BQ_DATA_FETCHER"
FETCHERS = "fetchers"
RULES = "rules"
INTERVALS = "intervals"
DIMENSIONS = "dimensions"
STATS_SERIES = "STATS_SERIES"
TIME_SERIES = "TIME_SERIES"
CROSS_SECTION = "CROSS_SECTION"
SPEC = "spec"
FUNCTION = "function"
THRESHOLD = "threshold"
THRESHOLD_DELTA = "threshold_delta"
METRIC = "metric"
RGT = "RELATIVE_GREATER_THAN"
RST = "RELATIVE_SMALLER_THAN"
RGTE = "RELATIVE_GREATER_THAN_EQUAL"
RSTE = "RELATIVE_SMALLER_THAN_EQUAL"
GT = "GREATER_THAN"
ST = "SMALLER_THAN"
GTE = "GREATER_THAN_EQUAL"
STE = "SMALLER_THAN_EQUAL"
IN = "IN"
STD_METHOD = "STD_METHOD"
LIST = "list"
FAIL_TASK = "fail_task"
ALWAYS_SEND = "always_send"
ACTIONS = "actions"
ADDRESS = "address"
SEND_MAIL = "SEND_MAIL"
PRINT = "PRINT"
MIN_ABS_DIFF = "min_abs_diff"
GRAPH = "graph"
SCALAR = "scalar"
BY_PASS_UPPER_LIMIT = "bypass_upper_limit"
